name: Turno de Marcaje

on:
  schedule:
    - cron: "10 12 * * 1-5" # 08:10 CLT (Lunes a Viernes)
    - cron: "30 21 * * 1-5" # 17:30 CLT (Lunes a Viernes)
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub UI

jobs:
  marcar-turno:
    runs-on: ubuntu-latest
    env:
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias (si existen)
        run: |
          if [ -s requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No hay dependencias que instalar"
          fi

      - name: Ejecutar script main.py
        run: |
          python main.py
